### ISSUE TITLE
Is renv compatible with .Rprofile customizations?

### ISSUE THREAD

**Issue by edavidaja** [batpigandme/idk-2020#1]
(this repo is an awesome idea.)

https://twitter.com/PeeltothePithy/status/1218263263890329600

**Comment by batpigandme** [comment]
Well the answer to this one is definitely I don't know! 😂
Step one: a meta-suggestion, have you asked on community.rstudio.com? I know a bunch of folks there are frequent users.

**Comment by batpigandme** [comment]
Check out the [Infrastructure](https://rstudio.github.io/renv/articles/renv.html#infrastructure) section of Introduction to renv.

It sounds like renv creates a project-specific `.Rprofile` (which should be committed to your version control system) in order to fire up for the project. In general, `.Rprofile` customizations are not great for reproducibility (which is kind of renv's bailiwick)—see [here](https://rstats.wtf/r-startup.html#rprofile) in What They Forgot. 

I'm gonna close this issue as I've reached the extent of my knowledge, and a more detailed answer from someone who knows more is better suited to [community.rstudio.com](https://community.rstudio.com/).

Good luck!
